nota1 = float (input("Insira sua primeira nota:"))
nota2 = float (input("Insira sua segunda nota:"))
nota3 = float (input("Insira sua terceira nota:"))
nota4 = float (input("Insira sua quarta nota:"))
nota_final = float ((nota1 + nota2 + nota3 + nota4)/4)
print(f"Sua nota final: {nota_final}")